In [21]:
from sklearn.datasets import make_multilabel_classification
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.multioutput import ClassifierChain

import pandas as pd
import numpy as np

In [22]:
df = pd.read_excel('menu_data.xlsx')
df.head()

메뉴               소스  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15
0   8       ['4', '5']  0  0  0  1  1  0  0  0  0   0   0   0   0   0   0
1  11      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   0
2  18      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   0
3   8       ['3', '5']  0  0  1  0  1  0  0  0  0   0   0   0   0   0   0
4   5  ['1', '3', '5']  1  0  1  0  1  0  0  0  0   0   0   0   0   0   0

In [24]:
X = df[['메뉴']]
X = X.to_numpy()
X, X.shape

(array([[ 8],
        [11],
        [18],
        ...,
        [ 4],
        [ 9],
        [ 9]], dtype=int64),
 (1318, 1))

In [25]:
y = df.iloc[:, 2:]
y = y.to_numpy()
y, y.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 1, 0, 0]], dtype=int64),
 (1318, 15))

In [26]:
X_train, X_test, y_train, y_test = train_test_split(
   X, y, random_state=0
)

In [28]:
base_lr = LogisticRegression(solver='lbfgs', random_state=0)
chain = ClassifierChain(base_lr, order='random', random_state=0, cv=10)
chain.fit(X_train, y_train).predict(X_test)

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [30]:
chain.predict_proba(X_test[:2]), y_test[:2]

(array([[0.31710075, 0.10412206, 0.19280632, 0.22997302, 0.18791875,
         0.13331075, 0.05943701, 0.01674985, 0.20741362, 0.08718274,
         0.0521262 , 0.07546876, 0.3430262 , 0.21384977, 0.01720413],
        [0.34171185, 0.0384937 , 0.22887834, 0.16430265, 0.34561452,
         0.14688826, 0.05375687, 0.00191371, 0.19462877, 0.06610285,
         0.03621645, 0.12137179, 0.37839331, 0.08722225, 0.00174335]]),
 array([[0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
        [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0]], dtype=int64))