In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import average_precision_score
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import hamming_loss
import warnings
warnings.filterwarnings(action='ignore')

# 메뉴

In [2]:
df = pd.read_excel('menu_data.xlsx')
df.head()

메뉴               소스  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15
0   8       ['4', '5']  0  0  0  1  1  0  0  0  0   0   0   0   0   0   0
1  11      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   0
2  18      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   0
3   8       ['3', '5']  0  0  1  0  1  0  0  0  0   0   0   0   0   0   0
4   5  ['1', '3', '5']  1  0  1  0  1  0  0  0  0   0   0   0   0   0   0

In [3]:
X = df[["메뉴"]].to_numpy()
y = np.asarray(df[df.columns[2:]])

In [4]:
X, X.shape

(array([[ 8],
        [11],
        [18],
        ...,
        [ 4],
        [ 9],
        [ 9]], dtype=int64),
 (1318, 1))

In [5]:
y, y.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 1, 0, 0]], dtype=int64),
 (1318, 15))

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [7]:
clf = MLPClassifier(activation='logistic', solver='lbfgs', random_state=42, max_iter=10000).fit(X_train, y_train)

In [8]:
clf.predict(X_test[:2])

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [9]:
y_test[:2]

array([[1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [10]:
y_pred = clf.predict(X_test)
hamming_loss(y_test, y_pred)

0.14626262626262626

In [11]:
ap_sum = 0
for i in range(y_test.shape[0]):
    ap_sum += average_precision_score(y_test[i], y_pred[i])
mAP = ap_sum/y_test.shape[0]
print(mAP)

0.23742424242424331


# 메뉴 + 빵, 치즈

In [12]:
df2 = pd.read_excel('menu_data(1).xlsx')
df2.head()

메뉴  빵  치즈               소스  1  2  3  4  5  6  7  8  9  10  11  12  13  14  \
0   8  3   1       ['4', '5']  0  0  0  1  1  0  0  0  0   0   0   0   0   0   
1  11  3   2      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   
2  18  3   2      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   
3   8  5   2       ['3', '5']  0  0  1  0  1  0  0  0  0   0   0   0   0   0   
4   5  5   1  ['1', '3', '5']  1  0  1  0  1  0  0  0  0   0   0   0   0   0   

   15  
0   0  
1   0  
2   0  
3   0  
4   0

In [13]:
X = df2[["메뉴", "빵", "치즈"]].to_numpy()
y = np.asarray(df2[df2.columns[4:]])

In [14]:
X, X.shape

(array([[ 8,  3,  1],
        [11,  3,  2],
        [18,  3,  2],
        ...,
        [ 3,  2,  2],
        [ 3,  5,  3],
        [ 3,  4,  4]], dtype=int64),
 (1325, 3))

In [15]:
y, y.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 1]], dtype=int64),
 (1325, 15))

In [16]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [17]:
clf = MLPClassifier(activation='logistic', solver='lbfgs', random_state=42, max_iter=10000).fit(X_train, y_train)

In [18]:
clf.predict(X_test[:5])

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [19]:
y_test[:5]

array([[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [20]:
y_pred = clf.predict(X_test)
hamming_loss(y_test, y_pred)

0.1429718875502008

In [21]:
ap_sum = 0
for i in range(y_test.shape[0]):
    ap_sum += average_precision_score(y_test[i], y_pred[i])
mAP = ap_sum/y_test.shape[0]
print(mAP)

0.3343206157965204


# 메뉴 + 빵, 치즈 + 설명

In [22]:
df3 = pd.read_excel('menu+des.xlsx')
df3.head()

Unnamed: 0  메뉴  빵  치즈               소스  랜치  마요네즈  스위트 어니언  허니 머스타드  스위트 칠리  \
0           0   8  3   1       ['4', '5']   0     0        0        1       1   
1           1  11  3   2      ['5', '14']   0     0        0        0       1   
2           2  18  3   2      ['5', '14']   0     0        0        0       1   
3           3   8  5   2       ['3', '5']   0     0        1        0       1   
4           4   5  5   1  ['1', '3', '5']   1     0        1        0       1   

   ...  367       368  369       370  371  372       373       374       375  \
0  ...  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
1  ...  0.0  0.086614  0.0  0.000000  0.0  0.0  0.099747  0.077295  0.000000   
2  ...  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
3  ...  0.0  0.000000  0.0  0.000000  0.0  0.0  0.000000  0.000000  0.000000   
4  ...  0.0  0.000000  0.0  0.142475  0.0  0.0  0.000000  0.000000  0.142475   

        376  
0  0.000000  
1  0.000000  
2  0.000000  
3  0.000000  
4  0.142475  

[5 rows x 397 columns]

In [23]:
X = df3.drop(columns=['Unnamed: 0','소스','랜치', '마요네즈', '스위트 어니언', '허니 머스타드', '스위트 칠리', '핫 칠리', '사우스웨스트 치폴레',
                         '머스타드', '홀스래디쉬', '올리브 오일', '레드와인식초', '소금', '후추', '스모크 바비큐', '이탈리안 드레싱'])
X = X.to_numpy()
X, X.shape

(array([[ 8.        ,  3.        ,  1.        , ...,  0.        ,
          0.        ,  0.        ],
        [11.        ,  3.        ,  2.        , ...,  0.07729536,
          0.        ,  0.        ],
        [18.        ,  3.        ,  2.        , ...,  0.        ,
          0.        ,  0.        ],
        ...,
        [ 3.        ,  2.        ,  2.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 3.        ,  5.        ,  3.        , ...,  0.        ,
          0.        ,  0.        ],
        [ 3.        ,  4.        ,  4.        , ...,  0.        ,
          0.        ,  0.        ]]),
 (1325, 380))

In [24]:
y = df2.iloc[:, 4:]
y = y.to_numpy()
y, y.shape

(array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 1, 0],
        ...,
        [0, 0, 0, ..., 1, 0, 0],
        [0, 0, 0, ..., 0, 1, 0],
        [0, 0, 0, ..., 0, 0, 1]], dtype=int64),
 (1325, 15))

In [25]:
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=42)

In [26]:
clf = MLPClassifier(activation='logistic', solver='lbfgs', random_state=42, max_iter=10000).fit(X_train, y_train)

In [27]:
clf.predict(X_test[:5])

array([[0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0]])

In [28]:
y_test[:5]

array([[0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0],
       [1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int64)

In [29]:
y_pred = clf.predict_proba(X_test)
hamming_loss(y_test, clf.predict(X_test))

0.15100401606425704

In [30]:
ap_sum = 0
for i in range(y_test.shape[0]):
    ap_sum += average_precision_score(y_test[i], y_pred[i])
mAP = ap_sum/y_test.shape[0]
print(mAP)

0.5822867296135363
