In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from skmultilearn.adapt import MLkNN
from sklearn.metrics import hamming_loss, accuracy_score

In [2]:
df = pd.read_excel('menu_data.xlsx')
df.head()

메뉴               소스  1  2  3  4  5  6  7  8  9  10  11  12  13  14  15
0   8       ['4', '5']  0  0  0  1  1  0  0  0  0   0   0   0   0   0   0
1  11      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   0
2  18      ['5', '14']  0  0  0  0  1  0  0  0  0   0   0   0   0   1   0
3   8       ['3', '5']  0  0  1  0  1  0  0  0  0   0   0   0   0   0   0
4   5  ['1', '3', '5']  1  0  1  0  1  0  0  0  0   0   0   0   0   0   0

In [29]:
X = df[["메뉴"]].to_numpy()
y = np.asarray(df[df.columns[2:]])

In [30]:
X

array([[ 8],
       [11],
       [18],
       ...,
       [ 3],
       [ 3],
       [ 3]], dtype=int64)

In [5]:
y

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 1, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int64)

In [31]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42)

In [32]:
# using Multi-label kNN classifier
mlknn_classifier = MLkNN()

In [33]:
mlknn_classifier.fit(X_train, y_train)

MLkNN()

In [39]:
print(accuracy_score(y_test, predicted))
print(hamming_loss(y_test, predicted))

0.03015075376884422
0.13752093802345058


In [44]:
for i in y_test:
    print(i)

[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 1 0 0 0 1 0 0]
[0 0 0 0 0 0 1 0 1 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
[1 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 1 0 1 0 0 0 1 0 0]
[0 0 0 1 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 1 0 0 0 1 0 0]
[1 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
[1 0 1 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 1 0 0 0 0 0]
[0 0 0 1 0 0 0 0 1 0 0 0 1 0 0]
[0 0 1 0 0 0 0 0 0 0 1 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 1 1 0 0]
[0 0 0 1 0 0 0 0 1 0 0 0 1 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 1 0 0 0 0 1 0 0 0 1 0 0]
[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
[0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 0 0 1]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[1 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 1 0 0 0 0 0 1 0 0 0 0 0 0]
[1 0 0 0 0 0 0 0 1 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1 1 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1 1 0 0]
[0 0 0 0 0 0 0 0 0 1 0 1 1 0 0]
[1 0 0 0

In [43]:
predicted = mlknn_classifier.predict(X_test)
for i in predicted.toarray():
    print(i)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
[0 0 0 1 0 0 0 0 0 0 0 0 0 1 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 1 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
[0 0 0 0